name: 'Get and cache dependencies'
description: 'Get and cache dependencies to speed up workflows'
inputs: 
  caching-input:
    description: 'Whether to cache dependencies or not'
    required: false
    default: 'true'
runs:
  using: 'composite'
  steps:
     -  name: Cache dependencies
        if: ${{ inputs.caching-input == 'true' }}
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
     -  name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true' || inputs.caching-input != 'true'
        run: npm ci
        shell: bash
